
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CP
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Map<String,Double> sifarisler = new LinkedHashMap<String,Double>();
    
    public void Sifarislerigoster(){
        
        String mesage = "";
        double value = 0;
        
        
        if(sifarisler.isEmpty()){
            mesage.equals("Sizin sifaris tapilmadi");
        }
        else{
            
            mesage +="       Sizin sifarisler\n\n\n";
        for(Map.Entry<String,Double> entry : sifarisler.entrySet() ){
            
            mesage += entry.getKey() +"\n";
            value += entry.getValue();
            
        }
        
        
        
        }
       
        mesage +="Qiymet : " + value +" AZN";
         JOptionPane.showMessageDialog(this, mesage);
         
        setVisible(false);
        
    }
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doner = new javax.swing.JCheckBox();
        shawarma = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cola = new javax.swing.JCheckBox();
        sifaris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        doner.setText("Chicken Doner - 3 AZN");
        doner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donerActionPerformed(evt);
            }
        });

        shawarma.setText("Shawarma - 4 AZN");

        ayran.setText("Ayran - 0.7 AZN");
        ayran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayranActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu");

        cola.setText("Cola - 1 AZN");
        cola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaActionPerformed(evt);
            }
        });

        sifaris.setText("Sifaris ver");
        sifaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifarisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ayran)
                            .addComponent(shawarma)
                            .addComponent(doner)
                            .addComponent(cola)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(sifaris)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(doner)
                .addGap(18, 18, 18)
                .addComponent(shawarma)
                .addGap(18, 18, 18)
                .addComponent(ayran)
                .addGap(18, 18, 18)
                .addComponent(cola)
                .addGap(27, 27, 27)
                .addComponent(sifaris)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donerActionPerformed

    private void ayranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayranActionPerformed

    private void colaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaActionPerformed

    private void sifarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifarisActionPerformed
        
        if(doner.isSelected()){
            sifarisler.put("Chicken Doner", 3.0);
        }
        else{
            sifarisler.remove("Chicken Doner");
        }
        if(shawarma.isSelected()){
            sifarisler.put("Shawarma", 4.0);
        }
        else{
            sifarisler.remove("Shawarma");
        }
        if(ayran.isSelected()){
            sifarisler.put("Ayran",0.7);
        }
        else{
            sifarisler.remove("Ayran");
        }
        if(cola.isSelected()){
            sifarisler.put("Cola", 1.0);
        }
        else{
            sifarisler.remove("Cola");
        }
        
        
        Sifarislerigoster();
    }//GEN-LAST:event_sifarisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox cola;
    private javax.swing.JCheckBox doner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox shawarma;
    private javax.swing.JButton sifaris;
    // End of variables declaration//GEN-END:variables
}
